export const STORAGE_KEYS = {
  users: 'bst:users',
  games: 'bst:games',
  scheme: 'bst:scheme',
  players: 'bst:players',
  matches: 'bst:matches',
  rankingTotals: 'bst:ranking',
  sessions: 'bst:sessions',
} as const

export const UI_TEXT = {
  appTitle: 'Backgammon Score Tracker',
  welcome: 'Welcome to Backgammon Score Tracker',
  addUser: 'Add Player',
  nameLabel: 'Name',
  add: 'Add',
  noUsers: 'No players yet.',
  users: 'Players',
  addGame: 'Add Match / Lines',
  playerA: 'Player A',
  playerB: 'Player B',
  lines: 'Lines',
  recordWinner: 'Record Winner',
  confirmWinner: 'Confirm Winner',
  selectWinner: 'Select the winner for this game.',
  close: 'Close',
  games: 'Matches',
  ranking: 'Rankings',
  rank: 'Rank',
  player: 'Player',
  totalLines: 'Total Lines',
  toggleToDark: 'Switch to Dark',
  toggleToLight: 'Switch to Light',
  darkMode: 'Dark mode',
  sessions: 'Sessions',
  createSession: 'Create Session',
  sessionDate: 'Session Date',
  selectPlayers: 'Select Players',
  create: 'Create',
  sessionsList: 'Sessions',
  addMatch: 'Add Match',
  addGameWin: 'Add Game Win',
  bestOfThree: 'Best of 3',
} as const

export type ColorScheme = 'light' | 'dark'

